language: generic
sudo: required

services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  - docker build -t vanhiep778/caro-admin -f Dockerfile .
  - docker tag vanhiep778/caro-admin registry.heroku.com/admin-caroo/web

deploy:
  provider: script
  script:
    # push to dockerhub & heroku
    docker push vanhiep778/caro-admin;
    docker push registry.heroku.com/admin-caroo/web;
    heroku container:release web --app admin-caroo
  on:
    branch: main
